// Hero query for fetching hero section data
export const heroQuery = `*[_type == "hero"][0]{
  title,
  subtitle,
  description,
  primaryButton{
    text,
    link
  },
  backgroundImageDesktop{
    asset->{
      _id,
      url,
      metadata{
        dimensions{
          width,
          height
        },
        palette{
          dominant{
            background,
            foreground
          }
        }
      }
    },
    hotspot,
    crop
  },
  backgroundImageTablet{
    asset->{
      _id,
      url,
      metadata{
        dimensions{
          width,
          height
        },
        palette{
          dominant{
            background,
            foreground
          }
        }
      }
    },
    hotspot,
    crop
  },
  backgroundImageMobile{
    asset->{
      _id,
      url,
      metadata{
        dimensions{
          width,
          height
        },
        palette{
          dominant{
            background,
            foreground
          }
        }
      }
    },
    hotspot,
    crop
  }
}`;